# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Tests

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "docs/**"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags: ["**"]
  workflow_dispatch:

jobs:
  render-dashboards:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        # test against a fixed older version we look to support and the latest
        # available version at https://github.com/google/go-jsonnet/releases/
        jsonnet-version:
          - "v0.20.0"
          - "latest"

    steps:
      - uses: actions/checkout@v6

      - name: Download jsonnet (go-jsonnet)
        run: |
          JSONNET_VERSION=${{ matrix.jsonnet-version }}
          if [ "$JSONNET_VERSION" == "latest" ]; then
              JSONNET_VERSION=$(curl -s https://api.github.com/repos/google/go-jsonnet/releases/latest | jq -r .tag_name)
              JSONNET_URL=https://github.com/google/go-jsonnet/releases/download/${JSONNET_VERSION}/go-jsonnet_Linux_x86_64.tar.gz
          else
              JSONNET_URL=https://github.com/google/go-jsonnet/releases/download/${JSONNET_VERSION}/go-jsonnet_${JSONNET_VERSION#v}_Linux_x86_64.tar.gz
          fi

          wget -qO- "$JSONNET_URL" | tar -xvz --one-top-level=$HOME/.local/bin

      - run: jsonnet --version

      - name: Render dashboards
        run: |
          mkdir rendered-dashboards
          dashboard_folders="dashboards"
          for file in `find $dashboard_folders -name '*.jsonnet'`
          do
              jsonnet -J vendor --output-file rendered-dashboards/`basename $file` $file
          done
